plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

def localProps = new Properties()
def localFile = rootProject.file('local.properties')
if (localFile.exists()) {
    localFile.withInputStream { localProps.load(it) }
}
def jevKey = localProps.getProperty('JEV_API_KEY', '')

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "dev.emreaktas.muteads"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 6
        versionName "2.0"
        buildConfigField "String", "JEV_API_KEY", "\"${jevKey}\""
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
